// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcoyikonbncypoororri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjb3lpa29uYm5jeXBvb3JvcnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODIwNzEsImV4cCI6MjA2ODY1ODA3MX0.niqrQiw1zlTkQMsC7kwh3UZcgi5VYH-hcUGSYJ-BBVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});